# Generated by Django 4.0.3 on 2023-02-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='website',
            field=models.CharField(max_length=120),
        ),
    ]
