# Generated by Django 4.1.7 on 2023-02-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0003_remove_website_date_remove_website_html_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_updated',
            new_name='dateUpdated',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='related_tag_data',
            new_name='relatedTagData',
        ),
        migrations.RemoveField(
            model_name='tagdata',
            name='availability_tag',
        ),
        migrations.RemoveField(
            model_name='tagdata',
            name='name_tag',
        ),
        migrations.RemoveField(
            model_name='tagdata',
            name='price_tag',
        ),
        migrations.RemoveField(
            model_name='tagdata',
            name='related_website',
        ),
        migrations.RemoveField(
            model_name='tagdata',
            name='url_tag',
        ),
        migrations.AddField(
            model_name='tagdata',
            name='availabilityFilter',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tagdata',
            name='availabilityTag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tagdata',
            name='nameFilter',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tagdata',
            name='nameTag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tagdata',
            name='priceFilter',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tagdata',
            name='priceTag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tagdata',
            name='relatedWebsite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagData', to='hunter.website'),
        ),
        migrations.AddField(
            model_name='tagdata',
            name='urlFilter',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tagdata',
            name='urlTag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
