# Generated by Django 4.1.7 on 2023-02-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0004_rename_date_created_product_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagdata',
            name='productFilter',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tagdata',
            name='productTag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
