# Generated by Django 4.1.7 on 2023-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0005_tagdata_productfilter_tagdata_producttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(null=True),
        ),
    ]
