# Generated by Django 4.1.7 on 2023-03-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0006_alter_product_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('is_superuser', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
